export const KNOWN_CREDENTIAL_KEYS = new Set([
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'BEDROCK_MODEL_ID',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'GEMINI_API_KEY',
  'GROK_API_KEY',
  'ELASTICSEARCH_URL',
  'ELASTICSEARCH_API_KEY',
  'ELASTICACHE_ENABLED',
  'ELASTICACHE_HOST',
  'ELASTICACHE_PORT',
  'ELASTICACHE_AUTH_TOKEN',
  'ELASTICACHE_TLS',
  'ELASTICACHE_KEY_PREFIX',
]);

export function isKnownCredentialKey(key: string): key is string {
  return KNOWN_CREDENTIAL_KEYS.has(key);
}
