// ECS deployment templates: workflow + task definition + readme + secrets
export const ECS_WORKFLOW_TEMPLATE = `# Generated by DevForge
name: Deploy to ECS

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          docker build -t {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }} .
          docker push {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition --task-definition {{TASK_FAMILY}} --query taskDefinition > task-def.json

      - name: Render new task definition with updated image
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def.json
          container-name: {{CONTAINER_NAME}}
          image: {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}

      - name: Deploy task definition to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: {{ECS_CLUSTER}}
          service: {{ECS_SERVICE}}
          task-definition: task-def.json
          wait-for-service-stability: true
`;

export const ECS_TASK_DEFINITION_TEMPLATE = `{
  "family": "{{TASK_FAMILY}}",
  "networkMode": "awsvpc",
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "{{CPU}}",
  "memory": "{{MEMORY}}",
  "executionRoleArn": "{{EXECUTION_ROLE_ARN}}",
  "containerDefinitions": [
    {
      "name": "{{CONTAINER_NAME}}",
      "image": "{{ECR_REGISTRY}}/{{IMAGE_NAME}}:latest",
      "portMappings": [ { "containerPort": {{PORT}}, "protocol": "tcp" } ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/{{TASK_FAMILY}}",
          "awslogs-region": "{{AWS_REGION}}",
          "awslogs-stream-prefix": "ecs"
        }
      }
    }
  ]
}`;

export const ECS_README_TEMPLATE =
  `# ECS deployment

This folder contains the ECS task definition used to deploy the service.

To deploy manually:

1. Build and push image to ECR:
   ` +
  '```sh\n' +
  `
   docker build -t {{ECR_REGISTRY}}/{{IMAGE_NAME}}:latest .
   docker push {{ECR_REGISTRY}}/{{IMAGE_NAME}}:latest
   ` +
  '```\n' +
  `
2. Register task definition:
   ` +
  '```sh\n' +
  `
   aws ecs register-task-definition --cli-input-json file://ecs/task-definition.json
   ` +
  '```\n' +
  `
3. Update service to use new task definition (replace cluster/service names):
   ` +
  '```sh\n' +
  `
   aws ecs update-service --cluster {{ECS_CLUSTER}} --service {{ECS_SERVICE}} --force-new-deployment
   ` +
  '```\n';

export const ECS_SECRETS_REQUIRED_TEMPLATE = `# ECS secrets and required values

- AWS_ROLE_ARN (recommended) or AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
- TASK_FAMILY: {{TASK_FAMILY}}
- ECS_CLUSTER: {{ECS_CLUSTER}}
- ECS_SERVICE: {{ECS_SERVICE}}
- EXECUTION_ROLE_ARN: {{EXECUTION_ROLE_ARN}}
`;

export default {
  ECS_WORKFLOW_TEMPLATE,
  ECS_TASK_DEFINITION_TEMPLATE,
  ECS_README_TEMPLATE,
  ECS_SECRETS_REQUIRED_TEMPLATE,
};
