// Consolidated EKS deployment templates (workflow + k8s manifests + secrets doc)
export const EKS_WORKFLOW_TEMPLATE = `# Generated by DevForge
name: Deploy to EKS

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }} .
          docker push {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name {{EKS_CLUSTER_NAME}} --region {{AWS_REGION}}

      - name: Deploy to EKS (rolling update)
        run: |
          kubectl set image deployment/{{APP_NAME}} {{APP_NAME}}={{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}
          kubectl rollout status deployment/{{APP_NAME}} --timeout=120s
`;

export const EKS_K8S_DEPLOYMENT_TEMPLATE = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          image: {{ECR_REGISTRY}}/{{IMAGE_NAME}}:latest
          ports:
            - containerPort: {{PORT}}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: {{PORT}}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
`;

export const EKS_K8S_SERVICE_TEMPLATE = `apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
    - protocol: TCP
      port: {{PORT}}
      targetPort: {{PORT}}
`;

export const EKS_K8S_INGRESS_TEMPLATE = `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
spec:
  rules:
    - host: {{DOMAIN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}
                port:
                  number: {{PORT}}
`;

export const EKS_SECRETS_REQUIRED_TEMPLATE = `# Required GitHub Actions Secrets for EKS Deployment

## Option A — OIDC (Recommended)

- AWS_ROLE_ARN — IAM Role ARN for GitHub Actions to assume via OIDC

## Option B — Long-lived keys (less preferred)

- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY

Cluster info:
- Cluster: {{EKS_CLUSTER_NAME}}
- Region:  {{AWS_REGION}}
`;

export default {
  EKS_WORKFLOW_TEMPLATE,
  EKS_K8S_DEPLOYMENT_TEMPLATE,
  EKS_K8S_SERVICE_TEMPLATE,
  EKS_K8S_INGRESS_TEMPLATE,
  EKS_SECRETS_REQUIRED_TEMPLATE,
};
