/**
 * Amazon EKS deployment templates for DevForge.
 *
 * Provides:
 *  - GitHub Actions CI/CD workflow (build → ECR push → EKS rolling deploy)
 *  - Kubernetes Deployment manifest
 *  - Kubernetes Service manifest (ClusterIP)
 *  - Kubernetes Ingress manifest
 *  - SECRETS_REQUIRED.md listing required AWS credentials
 */

export const EKS_WORKFLOW_TEMPLATE = `# Generated by DevForge — do not edit above this line
name: Deploy to Amazon EKS

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    outputs:
      image: \${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        id: build-image
        run: |
          docker build -t {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }} .
          docker push {{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}
          echo "image={{ECR_REGISTRY}}/{{IMAGE_NAME}}:\${{ github.sha }}" >> \$GITHUB_OUTPUT

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: {{AWS_REGION}}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name {{EKS_CLUSTER_NAME}} --region {{AWS_REGION}}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/{{APP_NAME}} {{APP_NAME}}=\${{ needs.build.outputs.image }}
          kubectl rollout status deployment/{{APP_NAME}} --timeout=120s
`;

export const EKS_K8S_DEPLOYMENT_TEMPLATE = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          image: {{ECR_REGISTRY}}/{{IMAGE_NAME}}:latest
          ports:
            - containerPort: {{PORT}}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: {{PORT}}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
`;

export const EKS_K8S_SERVICE_TEMPLATE = `apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{PORT}}
`;

export const EKS_K8S_INGRESS_TEMPLATE = `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{DOMAIN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}
                port:
                  number: 80
`;

export const EKS_SECRETS_REQUIRED_TEMPLATE = `# Required GitHub Actions Secrets for EKS Deployment

## Option A — OIDC (Recommended, least-privilege)

Configure GitHub OIDC trust in your AWS account so no long-lived keys are stored:

| Secret | Description |
|--------|-------------|
| \`AWS_ROLE_ARN\` | ARN of the IAM role GitHub Actions will assume via OIDC (e.g. \`arn:aws:iam::123456789012:role/github-actions-eks\`) |

The role needs the following IAM permissions:
- \`ecr:GetAuthorizationToken\`
- \`ecr:BatchCheckLayerAvailability\`, \`ecr:PutImage\`, \`ecr:InitiateLayerUpload\`, \`ecr:UploadLayerPart\`, \`ecr:CompleteLayerUpload\`
- \`eks:DescribeCluster\`
- \`eks:AccessKubernetesApi\` (via \`aws-auth\` ConfigMap binding)

## Option B — Long-lived keys (less preferred)

| Secret | Description |
|--------|-------------|
| \`AWS_ACCESS_KEY_ID\` | IAM access key ID |
| \`AWS_SECRET_ACCESS_KEY\` | IAM secret access key |

If using Option B, replace \`role-to-assume\` in the workflow with:
\`\`\`yaml
aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
\`\`\`

## Cluster name and region

Set these in the workflow variables (already substituted by DevForge):
- Cluster: \`{{EKS_CLUSTER_NAME}}\`
- Region:  \`{{AWS_REGION}}\`
`;
