// Jenkins Declarative Pipeline templates for all supported deployment targets.
// Uses the same {{variable}} placeholder + allowlist rendering pipeline as GitHub Actions templates.

export const JENKINS_BASE_CI_TEMPLATE = `// Generated by DevForge — Declarative Pipeline
// Requires: NodeJS plugin configured with tool name '{{jenkinsNodeTool}}'
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Pipeline completed successfully'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_VERCEL_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to Vercel
// Requires: NodeJS plugin, Vercel credentials in Jenkins
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        VERCEL_TOKEN     = credentials('vercel-token')
        VERCEL_ORG_ID    = credentials('vercel-org-id')
        VERCEL_PROJECT_ID = credentials('vercel-project-id')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }

        stage('Deploy to Vercel') {
            when {
                branch 'main'
            }
            steps {
                sh 'npx vercel --prod --token $VERCEL_TOKEN --yes'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Deployed to Vercel'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_RAILWAY_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to Railway
// Requires: NodeJS plugin, Railway token in Jenkins credentials
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        RAILWAY_TOKEN = credentials('railway-token')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }

        stage('Deploy to Railway') {
            when {
                branch 'main'
            }
            steps {
                sh 'npx railway up --service $JOB_NAME --environment production'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Deployed to Railway'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_RENDER_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to Render
// Requires: NodeJS plugin, Render deploy hook URL in Jenkins credentials
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        RENDER_DEPLOY_HOOK = credentials('render-deploy-hook')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }

        stage('Deploy to Render') {
            when {
                branch 'main'
            }
            steps {
                sh """
                    curl --request POST \\\\
                      --url "$RENDER_DEPLOY_HOOK" \\\\
                      --header 'Content-Type: application/json' \\\\
                      --data '{"gitCommitSha": "'$GIT_COMMIT'", "gitBranch": "'$GIT_BRANCH'"}'
                """
                echo 'Waiting for Render deployment...'
                sleep(time: 30, unit: 'SECONDS')
                echo '✓ Deployment triggered on Render'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Pipeline completed successfully'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_FIREBASE_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to Firebase
// Requires: NodeJS plugin, Firebase token in Jenkins credentials
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        FIREBASE_TOKEN = credentials('firebase-token')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }

        stage('Deploy to Firebase') {
            when {
                branch 'main'
            }
            steps {
                sh 'npx firebase-tools deploy --token $FIREBASE_TOKEN --non-interactive'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Deployed to Firebase'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_AWS_EC2_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to AWS EC2
// Requires: NodeJS plugin, SSH Agent plugin, AWS EC2 SSH key in Jenkins credentials
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        EC2_HOST     = credentials('aws-ec2-host')
        EC2_USERNAME = credentials('aws-ec2-username')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh '{{installCommand}}'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint --if-present || echo "No lint script"'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCommand}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCommand}}'
            }
        }

        stage('Deploy to EC2') {
            when {
                branch 'main'
            }
            steps {
                sshagent(credentials: ['aws-ec2-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'DEPLOY_SCRIPT'
                        cd ~/app
                        git pull origin main
                        {{installCommand}}
                        {{buildCommand}}
                        pm2 restart app || pm2 start "{{buildCommand}}" --name app
                        pm2 save
DEPLOY_SCRIPT
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✓ Deployed to EC2'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_AWS_ECS_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to AWS ECS
// Requires: NodeJS plugin, Docker, AWS CLI, AWS credentials in Jenkins
// Note: This pipeline uses IaC artifacts generated by DevForge (Terraform/CDK/boto3)
//       for infrastructure. The deploy stage only handles the application deployment.
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        AWS_DEFAULT_REGION = '{{AWS_REGION}}'
        ECR_REGISTRY       = '{{ECR_REGISTRY}}'
        IMAGE_NAME         = '{{IMAGE_NAME}}'
        ECS_CLUSTER        = '{{ECS_CLUSTER}}'
        ECS_SERVICE         = '{{ECS_SERVICE}}'
        TASK_FAMILY         = '{{TASK_FAMILY}}'
    }

    options {
        timeout(time: 45, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Test') {
            steps {
                sh '{{installCommand}}'
                sh '{{testCommand}}'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER ."
                sh "docker tag $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER $ECR_REGISTRY/$IMAGE_NAME:latest"
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServices' + 'CredentialsBinding', credentialsId: 'aws-credentials']]) {
                    sh "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY"
                    sh "docker push $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER"
                    sh "docker push $ECR_REGISTRY/$IMAGE_NAME:latest"
                }
            }
        }

        stage('Deploy to ECS') {
            when {
                branch 'main'
            }
            steps {
                withCredentials([[$class: 'AmazonWebServices' + 'CredentialsBinding', credentialsId: 'aws-credentials']]) {
                    // Download current task definition and update image
                    sh """
                        aws ecs describe-task-definition --task-definition $TASK_FAMILY \\
                          --query taskDefinition > task-def.json

                        # Update the image in the task definition
                        sed -i 's|"image":.*|"image": "'$ECR_REGISTRY'/'$IMAGE_NAME':'$BUILD_NUMBER'",|' task-def.json

                        aws ecs register-task-definition --cli-input-json file://task-def.json
                        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE \\
                          --force-new-deployment
                    """

                    // Wait for service stability
                    sh "aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
            sh "docker rmi $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER || true"
        }
        success {
            echo '✓ Deployed to ECS'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_AWS_EKS_DEPLOY_TEMPLATE = `// Generated by DevForge — Deploy to AWS EKS
// Requires: NodeJS plugin, Docker, AWS CLI, kubectl, AWS credentials in Jenkins
// Note: This pipeline uses IaC artifacts generated by DevForge (Terraform/CDK/boto3)
//       for infrastructure. The deploy stage only handles the application deployment.
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        AWS_DEFAULT_REGION  = '{{AWS_REGION}}'
        ECR_REGISTRY        = '{{ECR_REGISTRY}}'
        IMAGE_NAME          = '{{IMAGE_NAME}}'
        EKS_CLUSTER_NAME    = '{{EKS_CLUSTER_NAME}}'
        APP_NAME            = '{{APP_NAME}}'
    }

    options {
        timeout(time: 45, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Test') {
            steps {
                sh '{{installCommand}}'
                sh '{{testCommand}}'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER ."
                sh "docker tag $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER $ECR_REGISTRY/$IMAGE_NAME:latest"
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServices' + 'CredentialsBinding', credentialsId: 'aws-credentials']]) {
                    sh "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY"
                    sh "docker push $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER"
                    sh "docker push $ECR_REGISTRY/$IMAGE_NAME:latest"
                }
            }
        }

        stage('Deploy to EKS') {
            when {
                branch 'main'
            }
            steps {
                withCredentials([[$class: 'AmazonWebServices' + 'CredentialsBinding', credentialsId: 'aws-credentials']]) {
                    sh "aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION"
                    sh "kubectl set image deployment/$APP_NAME $APP_NAME=$ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER"
                    sh "kubectl rollout status deployment/$APP_NAME --timeout=120s"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
            sh "docker rmi $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER || true"
        }
        success {
            echo '✓ Deployed to EKS'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;

export const JENKINS_DOCKER_BUILD_TEMPLATE = `// Generated by DevForge — Build and Push Docker Image
// Requires: NodeJS plugin, Docker, Docker Hub credentials in Jenkins
pipeline {
    agent { label '{{jenkinsAgentLabel}}' }

    tools {
        nodejs '{{jenkinsNodeTool}}'
    }

    environment {
        DOCKER_HUB_CREDS = credentials('docker-hub-credentials')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Test') {
            steps {
                sh '{{installCommand}}'
                sh '{{testCommand}}'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:$BUILD_NUMBER ."
                sh "docker tag $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:$BUILD_NUMBER $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:latest"
            }
        }

        stage('Push to Docker Hub') {
            when {
                branch 'main'
            }
            steps {
                sh "echo $DOCKER_HUB_CREDS_PSW | docker login --username $DOCKER_HUB_CREDS_USR --password-stdin"
                sh "docker push $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:$BUILD_NUMBER"
                sh "docker push $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:latest"
            }
        }
    }

    post {
        always {
            cleanWs()
            sh "docker rmi $DOCKER_HUB_CREDS_USR/{{APP_NAME}}:$BUILD_NUMBER || true"
            sh 'docker logout || true'
        }
        success {
            echo '✓ Docker image built and pushed'
        }
        failure {
            echo '✗ Pipeline failed'
        }
    }
}
`;
// Phase 2 — Jenkins Job config.xml template
// Used by `devforge jenkins setup` to create pipeline jobs via the Jenkins REST API.
export const JENKINS_JOB_CONFIG_TEMPLATE = `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <actions>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobAction/>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction>
      <jobProperties/>
      <triggers/>
      <parameters/>
      <options/>
    </org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction>
  </actions>
  <description>Automated pipeline created by DevForge</description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <com.coravy.hudson.plugins.github.GithubProjectProperty>
      <projectUrl>https://github.com/{{githubOwner}}/{{githubRepo}}/</projectUrl>
      <displayName></displayName>
    </com.coravy.hudson.plugins.github.GithubProjectProperty>
    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
      <triggers>
        <com.cloudbees.jenkins.GitHubPushTrigger>
          <spec></spec>
        </com.cloudbees.jenkins.GitHubPushTrigger>
      </triggers>
    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition">
    <scm class="hudson.plugins.git.GitSCM">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>{{gitRemoteUrl}}</url>
          <credentialsId>{{jenkinsCredentialsId}}</credentialsId>
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/{{branch}}</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="empty-list"/>
      <extensions/>
    </scm>
    <scriptPath>Jenkinsfile</scriptPath>
    <lightweight>true</lightweight>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>
`;

// Phase 3 — Jenkins Configuration as Code (JCasC) template
// Generates a reproducible jenkins.yaml for fresh controller bootstrapping.
export const JENKINS_JCASC_TEMPLATE = `# Jenkins Configuration as Code (JCasC)
# Generated by DevForge — reproducible controller setup
# Place this file at $JENKINS_HOME/jenkins.yaml or mount via CASC_JENKINS_CONFIG

jenkins:
  systemMessage: "Jenkins configured by DevForge JCasC"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          # Password should be overridden via environment variable JENKINS_ADMIN_PASSWORD
          password: "\${JENKINS_ADMIN_PASSWORD:-changeme}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  globalNodeProperties:
    - envVars:
        env:
          - key: "DEVFORGE_MANAGED"
            value: "true"

tool:
  nodejs:
    installations:
      - name: "{{jenkinsNodeTool}}"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "{{nodeVersion}}"
                    npmPackagesRefreshHours: 72

unclassified:
  location:
    url: "{{jenkinsUrl}}"
  gitHubPluginConfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
        credentialsId: "github-token"
        manageHooks: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "{{jenkinsCredentialsId}}"
              username: "\${GITHUB_USERNAME}"
              password: "\${GITHUB_TOKEN}"
              description: "GitHub credentials for SCM checkout"
`;

export default {
  JENKINS_BASE_CI_TEMPLATE,
  JENKINS_VERCEL_DEPLOY_TEMPLATE,
  JENKINS_RAILWAY_DEPLOY_TEMPLATE,
  JENKINS_RENDER_DEPLOY_TEMPLATE,
  JENKINS_FIREBASE_DEPLOY_TEMPLATE,
  JENKINS_AWS_EC2_DEPLOY_TEMPLATE,
  JENKINS_AWS_ECS_DEPLOY_TEMPLATE,
  JENKINS_AWS_EKS_DEPLOY_TEMPLATE,
  JENKINS_DOCKER_BUILD_TEMPLATE,
  JENKINS_JOB_CONFIG_TEMPLATE,
  JENKINS_JCASC_TEMPLATE,
};
